language: node_js
node_js:
- '0.10'
- '0.12'
services:
- redis-server
before_script:
- npm install -g grunt-cli
deploy:
  provider: heroku
  api_key:
    secure: "qk4B79Q7eUf0WDCFU/vmErFiGjpP3PPRJdL0VErH3I5RJfEpdO4JsM85o6J/Kdma9VseeBKcTQrxo3Rse/DOKQArheWR6YMkF1uq2vwlZkfaha5wLVNeQuXotYOf2Uad2VSysnxHtGnpBQwPEqUs1YhrKh8zIGsRcwKN6taWZo4="
  app: beamquest-dev
  on:
    repo: soltycabbage/BeamQuest
