language: node_js
node_js:
  - "0.10"
before_script:
  - npm install -g grunt-cli
deploy:
  provider: heroku
  api_key:
    secure: eHPCNRCYBc6WkXefKnfCJRDhzTud2WTc9m6NxrFYLeIHhy7JyD1AmajcilZUXzcVInOLqo3xHuOXM2dn2wEJTI4NsZyB20EtWLqk3J4CngaHK0vQESiLDYmnyrnTm757wns7D/AqGn5nPirLtySMsHY0vMK905N+wDexgxtelbk=
  app: beamquest-dev
  on:
    repo: soltycabbage/BeamQuest
